/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import DAO.ConectDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class New_Provider extends javax.swing.JFrame {

    // LLAMAR A LA CLASE ConectDB
    ConectDB con = new ConectDB();

    /**
     * Creates new form New_Provider
     */
    public New_Provider() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../img/icono_app.png")).getImage());

        con.AbrirConexion();  //ABRIR LA CONEXIÓN
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        CONTRACT = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        CCHARGE = new javax.swing.JLabel();
        txt_cCharge = new javax.swing.JTextField();
        COUNTRY = new javax.swing.JLabel();
        txt_country = new javax.swing.JTextField();
        PHONE = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        SAVE = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("NEW PROVIDER");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 39, -1, -1));

        NAME.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 255, 255));
        NAME.setText("Name");
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, 30));

        txt_name.setBackground(new java.awt.Color(51, 51, 51));
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 100, 30));

        CONTRACT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CONTRACT.setForeground(new java.awt.Color(255, 255, 255));
        CONTRACT.setText("Contact");
        getContentPane().add(CONTRACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, 30));

        txt_contact.setBackground(new java.awt.Color(51, 51, 51));
        txt_contact.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, 30));

        CCHARGE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CCHARGE.setForeground(new java.awt.Color(255, 255, 255));
        CCHARGE.setText("CCharge");
        getContentPane().add(CCHARGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 70, 30));

        txt_cCharge.setBackground(new java.awt.Color(51, 51, 51));
        txt_cCharge.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_cCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 100, 30));

        COUNTRY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        COUNTRY.setForeground(new java.awt.Color(255, 255, 255));
        COUNTRY.setText("Country");
        getContentPane().add(COUNTRY, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 70, 30));

        txt_country.setBackground(new java.awt.Color(51, 51, 51));
        txt_country.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 100, 30));

        PHONE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PHONE.setForeground(new java.awt.Color(255, 255, 255));
        PHONE.setText("Phone");
        getContentPane().add(PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 70, 30));

        txt_phone.setBackground(new java.awt.Color(51, 51, 51));
        txt_phone.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 100, 30));

        SAVE.setBackground(new java.awt.Color(25, 25, 25));
        SAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar-A.png"))); // NOI18N
        SAVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAVE.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar-B.png"))); // NOI18N
        SAVE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar.png"))); // NOI18N
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 50, 50));

        CANCEL.setBackground(new java.awt.Color(25, 25, 25));
        CANCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no-A.png"))); // NOI18N
        CANCEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCEL.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no-B.png"))); // NOI18N
        CANCEL.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no.png"))); // NOI18N
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });
        getContentPane().add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 50, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_windows2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        // CANCEL
        Providers provider = null;
        try {
            provider = new Providers();
        } catch (SQLException ex) {
            Logger.getLogger(New_Provider.class.getName()).log(Level.SEVERE, null, ex);
        }
        provider.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CANCELActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // SAVE

        String Name, Contact, CCharge, Country, Phone;

        Name = txt_name.getText();
        Contact = txt_contact.getText();
        CCharge = txt_cCharge.getText();
        Country = txt_country.getText();
        Phone = txt_phone.getText();
        
        try {

            Statement s = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "INSERT INTO Providers (Name, Contact, CCharge, Country, Phone) VALUES ('" + Name + "','" + Contact + "','" + CCharge + "','" + Country + "','" + Phone + "')";
            int resultado = s.executeUpdate(query);

            query = "SELECT * FROM Providers";
            ResultSet r = s.executeQuery(query);
            r.first();
            txt_name.setText(r.getString("Name"));
            txt_contact.setText(r.getString("Contact"));
            txt_cCharge.setText(r.getString("CCharge"));
            txt_country.setText(r.getString("Country"));
            txt_phone.setText(r.getString("Phone"));
            
            Providers prov = new Providers();
            prov.setVisible(true);
            this.setVisible(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(New_Provider.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        JOptionPane.showMessageDialog(null, "Data saved successfully", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SAVEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Provider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Provider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Provider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Provider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new New_Provider().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(New_Provider.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CANCEL;
    private javax.swing.JLabel CCHARGE;
    private javax.swing.JLabel CONTRACT;
    private javax.swing.JLabel COUNTRY;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PHONE;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField txt_cCharge;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_country;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
