/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import DAO.ConectDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class New_Worker extends javax.swing.JFrame {
    
    // LLAMAR A LA CLASE ConectDB
    static ConectDB con = new ConectDB();

    /**
     * Creates new form Check_in
     */
    public New_Worker() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage (new ImageIcon(getClass().getResource("../img/icono_app.png")).getImage());
        
        con.AbrirConexion();  //ABRIR LA CONEXIÓN
        
        /**
         * Llamada al método combobox provider
         */
       
        String query = "SELECT * FROM Charges";
        ResultSet r;
        Statement s = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        r = s.executeQuery(query);
        
        DefaultComboBoxModel value = new DefaultComboBoxModel();
        while (r.next()) {
            value.addElement(r.getString("Name"));
        }
        
        ComboBox_position.setModel(value);
        
        /**
         * Llamada al método combobox category 2
         */
        
        String query2 = "SELECT * FROM Workdays";
        ResultSet r2;
        Statement s2 = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        r2 = s2.executeQuery(query2);
        
        DefaultComboBoxModel value2 = new DefaultComboBoxModel();
        while (r2.next()) {
            value2.addElement(r2.getString("Name"));
        }
        
        ComboBox_workday.setModel(value2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        SURNAME = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        POSITION = new javax.swing.JLabel();
        ComboBox_position = new javax.swing.JComboBox<>();
        WORKDAY = new javax.swing.JLabel();
        ComboBox_workday = new javax.swing.JComboBox<>();
        SALARY = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        DCONTRACT = new javax.swing.JLabel();
        txt_dcontract = new javax.swing.JTextField();
        BIRTHDATE = new javax.swing.JLabel();
        txt_birthdate = new javax.swing.JTextField();
        PHONE = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        LOGIN = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        SAVE = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("NEW WORKER");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        NAME.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 255, 255));
        NAME.setText("Name");
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, 30));

        txt_name.setBackground(new java.awt.Color(51, 51, 51));
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, 30));

        SURNAME.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SURNAME.setForeground(new java.awt.Color(255, 255, 255));
        SURNAME.setText("Surname");
        getContentPane().add(SURNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 70, 30));

        txt_surname.setBackground(new java.awt.Color(51, 51, 51));
        txt_surname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 30));

        POSITION.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        POSITION.setForeground(new java.awt.Color(255, 255, 255));
        POSITION.setText("Position");
        getContentPane().add(POSITION, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, 30));

        ComboBox_position.setBackground(new java.awt.Color(51, 51, 51));
        ComboBox_position.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBox_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, 30));

        WORKDAY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        WORKDAY.setForeground(new java.awt.Color(255, 255, 255));
        WORKDAY.setText("Workday");
        getContentPane().add(WORKDAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 70, 30));

        ComboBox_workday.setBackground(new java.awt.Color(51, 51, 51));
        ComboBox_workday.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_workday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBox_workday, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, 30));

        SALARY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SALARY.setForeground(new java.awt.Color(255, 255, 255));
        SALARY.setText("Salary");
        getContentPane().add(SALARY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 70, 30));

        txt_salary.setBackground(new java.awt.Color(51, 51, 51));
        txt_salary.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 100, 30));

        DCONTRACT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DCONTRACT.setForeground(new java.awt.Color(255, 255, 255));
        DCONTRACT.setText("DContract");
        getContentPane().add(DCONTRACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 70, 30));

        txt_dcontract.setBackground(new java.awt.Color(51, 51, 51));
        txt_dcontract.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_dcontract, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 100, 30));

        BIRTHDATE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BIRTHDATE.setForeground(new java.awt.Color(255, 255, 255));
        BIRTHDATE.setText("Birthdate");
        getContentPane().add(BIRTHDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 70, 30));

        txt_birthdate.setBackground(new java.awt.Color(51, 51, 51));
        txt_birthdate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 100, 30));

        PHONE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PHONE.setForeground(new java.awt.Color(255, 255, 255));
        PHONE.setText("Phone");
        getContentPane().add(PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, 30));

        txt_phone.setBackground(new java.awt.Color(51, 51, 51));
        txt_phone.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 100, 30));

        LOGIN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("Login");
        getContentPane().add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 70, 30));

        txt_login.setBackground(new java.awt.Color(51, 51, 51));
        txt_login.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 100, 30));

        PASSWORD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        PASSWORD.setText("Password");
        getContentPane().add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 70, 30));

        txt_password.setBackground(new java.awt.Color(51, 51, 51));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 100, 30));

        SAVE.setBackground(new java.awt.Color(25, 25, 25));
        SAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar-A.png"))); // NOI18N
        SAVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAVE.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar-B.png"))); // NOI18N
        SAVE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar.png"))); // NOI18N
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 50, 50));

        CANCEL.setBackground(new java.awt.Color(25, 25, 25));
        CANCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no-A.png"))); // NOI18N
        CANCEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCEL.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no-B.png"))); // NOI18N
        CANCEL.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no.png"))); // NOI18N
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });
        getContentPane().add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 50, 50));

        Background.setBackground(new java.awt.Color(51, 51, 51));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_windows2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        // CANCEL
        Workers worker = null;
        try {
            worker = new Workers();
        } catch (SQLException ex) {
            Logger.getLogger(New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        worker.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CANCELActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // SAVE
        
        String Name, Surname, Pos, Work, Salary, DContract, Birthdate, Phone, Login, Password;
        
        Name = txt_name.getText();
        Surname = txt_surname.getText();
        Pos = (String) ComboBox_position.getSelectedItem();
        int Position = getCodPosition(Pos);
        Work = (String) ComboBox_workday.getSelectedItem();
        int Workday = getCodWorkday(Work);
        Salary = txt_salary.getText();
        DContract = txt_dcontract.getText();
        Birthdate = txt_birthdate.getText();
        Phone = txt_phone.getText();
        Login = txt_login.getText();
        Password = txt_password.getText();
        
        try {
            
            Statement s = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
            ResultSet.CONCUR_UPDATABLE);
            String query = "INSERT INTO Workers (Name, Surname, Position, Workday, Salary, DContract, Birthdate, Phone, Login, Password) VALUES ('" + Name + "','" + Surname + "','" + Position + "','" + Workday + "','" + Salary + "','" + DContract + "','" + Birthdate + "','" + Phone + "','" + Login + "','" + Password + "')";
            int resultado = s.executeUpdate(query);
            
            query = "SELECT * FROM Workers";
            ResultSet r = s.executeQuery(query);
            r.first();
            txt_name.setText(r.getString("Name"));
            txt_surname.setText(r.getString("Surname"));
            ComboBox_position.setSelectedItem(getNombrePosition(r.getInt("Position")));
            ComboBox_workday.setSelectedItem(getNombreWorkday(r.getInt("Workday")));
            txt_salary.setText(r.getString("Salary"));
            txt_dcontract.setText(r.getString("DContract"));
            txt_name.setText(r.getString("Birthdate"));
            txt_name.setText(r.getString("Phone"));
            txt_name.setText(r.getString("Login"));
            txt_name.setText(r.getString("Password"));
            
            Workers worker = new Workers();
            worker.setVisible(true);
            this.setVisible(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(New_Product.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null,"Data saved successfully", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SAVEActionPerformed

    /**
     * Metodo que coje el código del position y devuelve su nombre.
     *
     * @param codigo - variable que contiene el código del position.
     * @return nombre - variable que contiene el nombre del position.
     */
    
    public static String getNombrePosition(int codigo) {

        String nombre;

        nombre = "";

        try {

            ResultSet r;
            Statement s = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String queryNombre = "SELECT Name FROM Charges WHERE IdPosition =" + codigo;
            r = s.executeQuery(queryNombre);
            r.first();
            nombre = r.getString("Name");

        } catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }

        return nombre;
    }
    
    /**
     * Método que coje el nombre del provider y devuelve su código.
     *
     * @param nombre - variable que contiene el nombre del position.
     * @return codigo - variable que contiene el código del position.
     *
     */
    public static int getCodPosition(String nombre) {

        int codigo = 0;

        try {
            ResultSet r;
            Statement s = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String queryNombre = "SELECT IdPosition FROM Charges WHERE Name ='" + nombre + "'";
            r = s.executeQuery(queryNombre);
            r.first();
            codigo = r.getInt("IdPosition");
        } catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }

        return codigo;
    }
    
    /**
     * Metodo que coje el código del Workday y devuelve su nombre.
     *
     * @param codigo - variable que contiene el código del Workday.
     * @return nombre - variable que contiene el nombre del Workday.
     */
    
    public static String getNombreWorkday(int codigo) {

        String nombre;

        nombre = "";

        try {

            ResultSet r2;
            Statement s2 = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String queryNombre = "SELECT Name FROM Workdays WHERE IdWorkday =" + codigo;
            r2 = s2.executeQuery(queryNombre);
            r2.first();
            nombre = r2.getString("Name");

        } catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }

        return nombre;
    }
    
    /**
     * Método que coje el nombre del Workday y devuelve su código.
     *
     * @param nombre - variable que contiene el nombre del Workday.
     * @return codigo - variable que contiene el código del Workday.
     *
     */
    public static int getCodWorkday(String nombre) {

        int codigo = 0;

        try {
            ResultSet r2;
            Statement s2 = con.getCon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String queryNombre = "SELECT IdWorkday FROM Workdays WHERE Name ='" + nombre + "'";
            r2 = s2.executeQuery(queryNombre);
            r2.first();
            codigo = r2.getInt("IdWorkday");
        } catch (SQLException ex) {
            Logger.getLogger(Workers.class.getName()).log(Level.SEVERE, null, ex);
        }

        return codigo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new New_Worker().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(New_Worker.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BIRTHDATE;
    private javax.swing.JLabel Background;
    private javax.swing.JButton CANCEL;
    private javax.swing.JComboBox<String> ComboBox_position;
    private javax.swing.JComboBox<String> ComboBox_workday;
    private javax.swing.JLabel DCONTRACT;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel PASSWORD;
    private javax.swing.JLabel PHONE;
    private javax.swing.JLabel POSITION;
    private javax.swing.JLabel SALARY;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel SURNAME;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel WORKDAY;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txt_birthdate;
    private javax.swing.JTextField txt_dcontract;
    private javax.swing.JTextField txt_login;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
