/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.ImageIcon;

/**
 *
 * @author Javier
 */
public class New_Line_Sale extends javax.swing.JFrame {

    /**
     * Creates new form New_Lines_Sale
     */
    public New_Line_Sale() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage (new ImageIcon(getClass().getResource("../img/icono_app.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        ID_SALE = new javax.swing.JLabel();
        ComboBox_idSale = new javax.swing.JComboBox<>();
        PRODUCT = new javax.swing.JLabel();
        ComboBox_product = new javax.swing.JComboBox<>();
        TRADEMARK = new javax.swing.JLabel();
        ComboBox_trademark = new javax.swing.JComboBox<>();
        SIZE = new javax.swing.JLabel();
        ComboBox_size = new javax.swing.JComboBox<>();
        PRICE = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        CANTITY = new javax.swing.JLabel();
        txt_cantity = new javax.swing.JTextField();
        SAVE = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("NEW LINE SALE");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        ID_SALE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ID_SALE.setForeground(new java.awt.Color(255, 255, 255));
        ID_SALE.setText("ID Sale");
        getContentPane().add(ID_SALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, 30));

        ComboBox_idSale.setBackground(new java.awt.Color(51, 51, 51));
        ComboBox_idSale.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_idSale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBox_idSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, 30));

        PRODUCT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PRODUCT.setForeground(new java.awt.Color(255, 255, 255));
        PRODUCT.setText("Product");
        getContentPane().add(PRODUCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, 30));

        ComboBox_product.setBackground(new java.awt.Color(51, 51, 51));
        ComboBox_product.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBox_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, 30));

        TRADEMARK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TRADEMARK.setForeground(new java.awt.Color(255, 255, 255));
        TRADEMARK.setText("Trademark");
        getContentPane().add(TRADEMARK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 70, 30));

        ComboBox_trademark.setBackground(new java.awt.Color(51, 51, 51));
        ComboBox_trademark.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_trademark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBox_trademark, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 100, 30));

        SIZE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SIZE.setForeground(new java.awt.Color(255, 255, 255));
        SIZE.setText("Size");
        getContentPane().add(SIZE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 70, 30));

        ComboBox_size.setBackground(new java.awt.Color(51, 51, 51));
        ComboBox_size.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_sizeActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_size, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 100, 30));

        PRICE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PRICE.setForeground(new java.awt.Color(255, 255, 255));
        PRICE.setText("Price");
        getContentPane().add(PRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 70, 30));

        txt_price.setBackground(new java.awt.Color(51, 51, 51));
        txt_price.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 100, 30));

        CANTITY.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CANTITY.setForeground(new java.awt.Color(255, 255, 255));
        CANTITY.setText("Cantity");
        getContentPane().add(CANTITY, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 70, 30));

        txt_cantity.setBackground(new java.awt.Color(51, 51, 51));
        txt_cantity.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_cantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 100, 30));

        SAVE.setBackground(new java.awt.Color(25, 25, 25));
        SAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar-A.png"))); // NOI18N
        SAVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAVE.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar-B.png"))); // NOI18N
        SAVE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_guardar.png"))); // NOI18N
        getContentPane().add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 50, 50));

        CANCEL.setBackground(new java.awt.Color(25, 25, 25));
        CANCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no-A.png"))); // NOI18N
        CANCEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCEL.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no-B.png"))); // NOI18N
        CANCEL.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_no.png"))); // NOI18N
        getContentPane().add(CANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 50, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_windows2.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_sizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Line_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Line_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Line_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Line_Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Line_Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CANCEL;
    private javax.swing.JLabel CANTITY;
    private javax.swing.JComboBox<String> ComboBox_idSale;
    private javax.swing.JComboBox<String> ComboBox_product;
    private javax.swing.JComboBox<String> ComboBox_size;
    private javax.swing.JComboBox<String> ComboBox_trademark;
    private javax.swing.JLabel ID_SALE;
    private javax.swing.JLabel PRICE;
    private javax.swing.JLabel PRODUCT;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel SIZE;
    private javax.swing.JLabel TRADEMARK;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField txt_cantity;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
